apiVersion: v1
kind: Template
labels:
  createdBy: xl-release-template
metadata:
  annotations:
    openshift.io/display-name: XL Release
    description: |-
      Automate, orchestrate and get visibility into your release pipelines — at enterprise scale
      Manage the most advanced release pipelines with ease:
      * Plan, automate, and analyze the entire software release pipeline
      * Control and optimize software delivery
      * Always know the status of automated and manual steps across the release pipeline
      * Identify bottlenecks, reduce errors, and lower the risk of release failures
    iconClass: icon-xebialabs
    tags: instant-app,xl-release,xebialabs,devops,ci-cd
    openshift.io/provider-display-name: XebiaLabs
    openshift.io/documentation-url: https://docs.xebialabs.com/xl-release/
    openshift.io/support-url: https://support.xebialabs.com/
  name: xl-release
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: xebialabs/xl-release:${APPLICATION_VERSION}
      name: xl-release-${APPLICATION_VERSION}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${APPLICATION_NAME}-user
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      recreateParams: {}
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: ADMIN_PASSWORD
            value: ${ADMIN_PASSWORD}
          - name: SERVER_URL
            value: "https://${XLR_HOSTNAME}"
          image: xl-release
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 5516
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: xl-release
          ports:
          - containerPort: 5516
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 5516
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccount: ${APPLICATION_NAME}-user
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - xl-release
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:xl-release-${APPLICATION_VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 5516-http
      port: 5516
      protocol: TCP
      targetPort: 5516
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  spec:
    host: ${XLR_HOSTNAME}
    port:
      targetPort: 5516-http
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}
parameters:
- description: The name for the application. The service will be named like the application.
  displayName: Application name.
  name: APPLICATION_NAME
  value: xl-release
- description: (Major) Version of XL Release to deploy
  displayName: XL Release version
  name: APPLICATION_VERSION
- description: Password for the XL Release 'admin' user. Must be at least 8 characters
    long.
  displayName: XL Release Admin User Password
  name: ADMIN_PASSWORD
  from: '[a-zA-Z0-9]{8}'
  generate: expression
- description: Hostname for the XL Release application.
  displayName: XL Release host name
  name: XLR_HOSTNAME
